### PR TITLE
ARCH-255: Update edx-drf-extensions imports.

### PR DESCRIPTION
**Pull request by robrap**
ARCH-255

### CODE REVIEW

**Comment by nasthagiri** [comment]
@schenedx Looks like your team has recently pushed changes to this repo.  The Arch team would like to upgrade one of its dependent libraries.  Questions:

1. The master branch (and hence this PR as well) is failing on Travis.  The underlying issue doesn't seem to have been solved for several months.  Should we ignore those errors and move on?

**Comment by nasthagiri** [comment]
FYI @Qubad786 - see comment above - in case you're still working in this area.

**Comment by schenedx** [comment]
@nasthagiri Yes. We should ignore the errors and merge.
That said. this also mean we should talk about auth change in veda. Even if we merge this change, it doesn't mean this change will be automatically deployed to production. The deployment is pure manual. I need to know a date for this change to be deployed.

**Comment by nasthagiri** [comment]
@robrap Given @schenedx's response, we can go ahead and merge this PR - assuming other related dependencies are also added if needed.

**Comment by robrap** [comment]
@schenedx: All tests from the following file are failing:
```
control/tests/test_file_discovery.py FFFFFFFFFF
```
I can merge my change, but I'd like to propose that the following be done:
Add a ticket titled "Video Pipeline has no test coverage for file discovery".  That can point to the PR where test_file_discovery.py gets deleted because they are all failing.  This will at least get master back to Green so the rest of your tests can protect the repo.  Thoughts?

**Comment by schenedx** [comment]
@robrap That's not the only test file which contains failed tests. That said, I am fine having a ticket to fix all the unit tests associated with this repo. Created at EDUCATOR-3570

**Comment by robrap** [comment]
Removed failing tests in separate PR (https://github.com/edx/edx-video-pipeline/pull/130). :)
FYI: @nasthagiri

**Comment by robrap** [comment]
@schenedx: FYI: I'll leave the codecov settings as-is.  That way PR will continue to be red due to the very low codecov, but at least the Tracis CI builds will be green.  This particular change doesn't require a special deployment.  As @nasthagiri mentioned, we will need to plan a deployment for some future work.

**Pull request merged**
