### PR TITLE
Handle some exceptional cases.

### PR DESCRIPTION
**Pull request by armbox**
fix for some exceptional cases.

Thanks,

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @armbox! I've created [OSPR-2821](https://openedx.atlassian.net/browse/OSPR-2821) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](http://open.edx.org/sites/default/files/wysiwyg/individual-contributor-agreement.pdf)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by natabene** [comment]
@armbox  Thank you for the contribution! When you have a chance, could you please send in a signed Contributor Agreement mentioned in the earlier comment? You only need to do this once and we can then review all your future code contributions. Thanks

**Comment by armbox** [comment]
Sent it already.
Thanks,

**Comment by natabene** [comment]
@armbox  We have added your user to our records and can now review your code going forward.
@schenedx Would you like to take a look?

**Comment by edx-webhook** [comment]
Thanks for the pull request, @armbox! I've created [OSPR-3596](https://openedx.atlassian.net/browse/OSPR-3596) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@fysheets Is this something you team can review?

**Comment by fysheets** [comment]
@armbox I know that this PR has been open for a while, so I was wondering if you could please provide more context here? Why are you making these changes, what are you hoping to resolve with these changes? We have been working to improve this system and some of these changes may no longer be relevant based on recent fixes internally. It is hard to know what the goal of these fixes is without more information.

Thank you

**Comment by edx-webhook** [comment]
@armbox Even though your pull request wasn’t merged, please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-video-pipeline&entry.867055334=https://github.com/edx/edx-video-pipeline/pull/134&entry.1484655318=https://github.com/armbox&entry.752974735=2018-11-27+04:52&entry.1917517419=2019-07-26+04:44&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
