### PR TITLE
Add migrations folder

### PR DESCRIPTION
**Pull request by yro**
### Description
Add migrations folder to repo

### Testing
- [ ] Unit tests

### Reviewers
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
- [ ] Code review: @muzaffaryousaf 

FYI: @edx/educator-neem @edx/educator-mallow

### Post-review
- [ ] Rebase and squash commits

### CODE REVIEW

**Comment by muzaffaryousaf** [comment]
@yro are these from production ?

**Comment by yro** [comment]
@muzaffaryousaf They are -- but I think not having a migration folder to begin with made the initial migration larger than we had expected. I don't have a ton of experience with these (other than django auto-migrations), so if they look wrong, let me know.

**Comment by muzaffaryousaf** [comment]
@greg The initial migration looks okay to me but my concern is , it should be similar to what we have on production otherwise production will be broken when we make a release.

**Comment by muzaffaryousaf** [comment]
@yro ^^

**Comment by yro** [comment]
@muzaffaryousaf I ran this one against production and it said "no changes", so I think it's ok.

**Comment by yro** [comment]
@muzaffaryousaf I think that it's not in gitignore?

**Comment by muzaffaryousaf** [comment]
Nvm, they are in our feature branch.

**Comment by yro** [comment]
@muzaffaryousaf 👍

**Pull request merged**
